### PR TITLE
WIP: Code of conduct

### LINKED ISSUE #9: Add contributor guidelines and CoC

### PR DESCRIPTION
**Pull request by jarrodmillman**
NOT READY TO MERGE

I adapted this text:
- http://scipy.github.io/devdocs/dev/conduct/code_of_conduct.html

Fixes #9

- need discussion
- need agreement
- need a committee
- need email address

### CODE REVIEW

**Comment by choldgraf** [comment]
Anything in particular you're concerned about that needs a lookover? As long as this is something that matches what the broader scipy community things works well, I'm +1

**Review by camillescott — APPROVED** [review]
Other than the empty committee, this looks good to me!

**Comment by jarrodmillman** [comment]
We need to fill the committee and get an email address (I figure a committee member should do this).  Since the "code of conduct should be honored" by all of us, I decided I should make sure everyone had an opportunity to view it before we merged it (even though I adapted it directly from the SciPy code of conduct).

Would @choldgraf and @camillescott be willing to serve on the committee?  I am happy to volunteer as well, unless someone else would like to.

**Comment by camillescott** [comment]
Yup, I'm down to serve.

**Comment by jarrodmillman** [comment]
Great!  I just added the two of us to the PR.  We need a third.

**Review by dschult — APPROVED** [review]
This looks good -- I'm no expert but it seems to cover what I would want it to cover.  I can be on the committee too.

**Comment by jarrodmillman** [comment]
I added Dan as the third committee member.  I still need to add an email address, which I will do later tonight.  I would also like to wait another day to make sure everyone has the opportunity to comment (if they wish).

**Pull request closed without merging**
