### PR TITLE
ENH: first pass at creating a NXArtist class

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
Check out the node_picker example on this branch!

**Comment by choldgraf** [comment]
nice!!! works great for me! are you ready for merge?

Here's a gif for others (don't pay attention to the absolute mouse cursor location, it's my GIF recording software)

**Comment by camillescott** [comment]
Wow, this is awesome!

**Comment by tacaswell** [comment]
I am happy to have this merged.  Not perfect (like lacking tests and doc strings) but still early days.

**Comment by camillescott** [comment]
Cool, I'll go ahead and merge. We're early enough along that we've got plenty of credit to spend on technical debt in exchange for cool features and API build out ;)

**Comment by choldgraf** [comment]
I beat ya to it ;-)

**Comment by camillescott** [comment]
Just saw that 😅

**Pull request merged**
